development:

  #ROLES 
  rol_administrador: 1
  rol_operador: 3
  rol_super: 6
  
  #sistemas
  sistema_RUE: 1
  
  #TIPOS ELEMENTOS INTERFAZ
  radio_button: 1
  check_box: 2
  text: 3
  combo_box: 4
  
  #TIPOS DATO
  tipo_dato_numerico: 1
  tipo_dato_texto: 2
 
  #TIPOS DOCUMENTOS
  certificado_nacimiento: 6
  sin_documento: 5
  cedula_identidad: 1

  #TIPOS DOCUMENTOS RESOLUCIONES
  constancia: 1
  resolucion: 2
  otros: 3


#ESTADO TORNEO DETALLE
  estado_torneo_detalle_activo: 1

#ESTADO TORNEOS
  estado_torneo_id: 1  

#ESTADO INSCRIPCIONES
  estado_inscripcion_activo: 1
  

production:

  #ROLES 
  rol_administrador: 1
  rol_operador: 3
  rol_super: 6
   
  #sistemas
  sistema_RUE: 1
  
  #TIPOS ELEMENTOS INTERFAZ
  radio_button: 1
  check_box: 2
  text: 3
  combo_box: 4
  
  #TIPOS DATO
  tipo_dato_numerico: 1
  tipo_dato_texto: 2
 
  #TIPOS DOCUMENTOS
  certificado_nacimiento: 6
  sin_documento: 5
  cedula_identidad: 1

  #TIPOS DOCUMENTOS RESOLUCIONES
  constancia: 1
  resolucion: 2
  otros: 3

  #ESTADO TORNEO DETALLE
  estado_torneo_detalle_activo: 1

  #ESTADO TORNEOS
  estado_torneo_id: 1

  #ESTADO INSCRIPCIONES
  estado_inscripcion_activo: 1

 