development:

  #ROLES 
  rol_administrador: 1
  rol_operador: 3
  rol_super: 6
  
  #sistemas
  sistema_RUE: 1
  
  #TIPOS ELEMENTOS INTERFAZ
  radio_button: 1
  check_box: 2
  text: 3
  combo_box: 4
  
  #TIPOS DATO
  tipo_dato_numerico: 1
  tipo_dato_texto: 2
 
  #TIPOS DOCUMENTOS
  certificado_nacimiento: 6
  sin_documento: 5
  cedula_identidad: 1

  #TIPOS DOCUMENTOS RESOLUCIONES
  constancia: 1
  resolucion: 2
  otros: 3

  #ESTADOS GANADOS
  estado_ganado_activo: 1
  estado_ganado_inactivo: 2
  estado_ganado_en_celo: 3
  estado_ganado_en_reproduccion: 4
  estado_ganado_prenhado: 5
  estado_ganado_en_proceso_venta: 6
  estado_ganado_vendido: 7
  estado_ganado_enfermo: 8
  estado_ganado_muerto: 9
  estado_ganado_faena: 10
  estados_ganados_predeterminados: [1,2,3,4,5,6,7,8,9,10]


#ESTADO TORNEO DETALLE
estado_torneo_detalle_activo: 1
  

production:

  #ROLES 
  rol_administrador: 1
  rol_operador: 3
  rol_super: 6
   
  #sistemas
  sistema_RUE: 1
  
  #TIPOS ELEMENTOS INTERFAZ
  radio_button: 1
  check_box: 2
  text: 3
  combo_box: 4
  
  #TIPOS DATO
  tipo_dato_numerico: 1
  tipo_dato_texto: 2
 
  #TIPOS DOCUMENTOS
  certificado_nacimiento: 6
  sin_documento: 5
  cedula_identidad: 1

  #TIPOS DOCUMENTOS RESOLUCIONES
  constancia: 1
  resolucion: 2
  otros: 3

  
  #ESTADOS GANADOS
  estado_ganado_activo: 1
  estado_ganado_inactivo: 2
  estado_ganado_en_celo: 3
  estado_ganado_en_reproduccion: 4
  estado_ganado_prenhado: 5
  estado_ganado_en_proceso_venta: 6
  estado_ganado_vendido: 7
  estado_ganado_enfermo: 8
  estado_ganado_muerto: 9
  estado_ganado_faena: 10
  estados_ganados_predeterminados: [1,2,3,4,5,6,7,8,9,10]

  #ESTADO TORNEO DETALLE
  estado_torneo_detalle_activo: 1

 